### ISSUE TITLE
Cant figure out how to connect a ftp server to solder. 

### ISSUE THREAD

**Issue by TylerBuza** [JadianGaming/Solder.io-One-Click-DigitalOcean-App#1]

**Comment by JadianRadiator** [comment]
I don't know how to help you.
I only made this github page for it so I'm the first point of contact in-case the issue is caused by something I bungled up in making the image.
https://www.digitalocean.com/community/tutorials/how-to-set-up-vsftpd-for-a-user-s-directory-on-ubuntu-18-04

**Comment by TylerBuza** [comment]
I figured it out, appreciate the droplet. Great work.
